from typing import List, Optional
from pydantic import BaseModel, Field, field_validator


class QueryRequest(BaseModel):
    question: str = Field(..., min_length=1, description="The query question asked by the user.")

    @field_validator("question")
    @classmethod
    def validate_question(cls, v: str) -> str:
        cleaned = v.strip()
        if not cleaned:
            raise ValueError("Question cannot be empty or only whitespace.")
        return cleaned


class SourceItem(BaseModel):
    document: str = Field(..., description="Source document file name")
    page: int = Field(..., description="Page number in the source document")
    snippet: Optional[str] = Field(None, description="Relevant text snippet from source")


class QueryResponse(BaseModel):
    answer: str = Field(..., description="Grounded answer generated by local LLM")
    sources: List[SourceItem] = Field(default_factory=list, description="List of source document citations")


class HealthResponse(BaseModel):
    status: str
    vector_store_loaded: bool
    ollama_connected: bool
    embedding_model: str
    collection_name: str
    total_documents_indexed: int
